"""
This module contains the logic for the About dialog window.
"""

from PySide6 import QtWidgets as Qtw
from .about_ui.about_dialog import Ui_AboutDialog

class AboutDialog(Qtw.QDialog, Ui_AboutDialog):
    """
    Presents a simple "About" dialog with application information.

    This class inherits from QDialog (the base class for dialog windows) and
    Ui_AboutDialog (the auto-generated class from Qt Designer). This multiple
    inheritance pattern is standard for connecting UI definitions to application logic.
    """
    def __init__(self):
        """
        Initializes the AboutDialog.
        """
        super().__init__()
        # The setupUi method is generated by Qt Designer and is responsible for
        # creating and laying out all the widgets defined in the .ui file.
        self.setupUi(self)

        # Set the window title and text for the labels.
        self.setWindowTitle("About StudWalls")
        self.labelTitle.setText("StudWalls")
        self.labelVersion.setText("Version 0.1.0")
        
        # The buttonBox is a standard QDialogButtonBox. We connect its `accepted`
        # signal (emitted when the OK button is clicked) to the dialog's built-in
        # `accept` slot, which closes the dialog and returns a QDialog.Accepted result.
        self.buttonBox.accepted.connect(self.accept)